GroupProject/ViewModels/PcPartsViewModel.cs
using DataAccess.Core.Entities;
using System.Collections.Generic;
using System;
using System.Linq;
using System.Web;

namespace GroupProject.ViewModels
{
    public class PcPartsViewModel
    {
        public IEnumerable<Company> Companies { get; set; }
        public Case Case { get; set; }
        public CPU CPU { get; set; }
        public GPU GPU { get; set; }
        public Motherboard Motherboard { get; set; }
        public PSU PSU { get; set; }
        public RAM RAM { get; set; }
        public Storage Storage { get; set; }
    }
}

GroupProject/Controllers/CPUsController.cs
using DataAccess.Core.Entities;
using DataAccess.Core.Interfaces;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class CPUsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CPUsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Cpus
        public ActionResult Index()
        {
            var cpus = _unitOfWork.Cpus.GetAll();
            return View(cpus.ToList());
        }

        // GET: Cpus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CPU cpu = _unitOfWork.Cpus.GetById(id);
            if (cpu == null)
            {
                return HttpNotFound();
            }
            return View(cpu);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupProject/Controllers/GPUsController.cs
using DataAccess.Core.Entities;
using DataAccess.Core.Interfaces;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class GPUsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public GPUsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: GPUs
        public ActionResult Index()
        {
            var gpus = _unitOfWork.Gpus.GetAll();
            return View(gpus.ToList());
        }

        // GET: GPUs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GPU gpu = _unitOfWork.Gpus.GetById(id);
            if (gpu == null)
            {
                return HttpNotFound();
            }
            return View(gpu);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupProject/Controllers/HomeController.cs
using DataAccess.Core.Interfaces;
using GroupProject.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            SuggestedBuildsViewModel viewmodel = new SuggestedBuildsViewModel()
            {
                SuggestedBuilds = _unitOfWork.SuggestedBuilds.GetAll().Take(4),
                Builds = _unitOfWork.Builds.GetAll().Take(4)
            };

            return View(viewmodel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult PCParts()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }
    }
}

GroupProject/Controllers/PSUsController.cs
using DataAccess.Core.Entities;
using DataAccess.Core.Interfaces;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class PSUsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PSUsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Admin/PSUs
        public ActionResult Index()
        {
            var pSUs = _unitOfWork.Psus.GetAll();
            return View(pSUs.ToList());
        }

        // GET: Admin/PSUs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PSU psu = _unitOfWork.Psus.GetById(id);

            if (psu == null)
            {
                return HttpNotFound();
            }
            return View(psu);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupProject/Controllers/RAMsController.cs
using DataAccess.Core.Entities;
using DataAccess.Core.Interfaces;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    public class RAMsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RAMsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: RAMs
        public ActionResult Index()
        {
            var rams = _unitOfWork.Rams.GetAll();
            return View(rams.ToList());
        }

        // GET: RAMs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RAM ram = _unitOfWork.Rams.GetById(id);

            if (ram == null)
            {
                return HttpNotFound();
            }
            return View(ram);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupProject/Views/Home/About.cshtml
@*@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>*@


<section class="project-section">
    <h1 class="project-heading">Meet our team</h1>
    <div class="project-container">
        <div class="project-card">
            <img src="~/img/G2R_profile.jpg" class="project-img" alt="">
            <div class="project-content">
                <h1 class="project-title">Stavros Sountris</h1>
                <p class="project-info">
                    Back-end developer, patient and co-operative.
                    In his free time, he likes photoshooting, YouTube video creation
                    and live streaming when working his personal projects.
                </p>
                <div class="project-btn-grp">
                    <a href='https://github.com/StavrosG2R' target="_blank" class="project-btn github"><button class="project-btn github">github</button></a>
                    <a href="https://www.linkedin.com/in/stavros-sountris-271292219/" target="_blank" class="project-btn live"><button class="project-btn live">LinkedIn profile</button></a>
                </div>
            </div>
        </div>
        <div class="project-card">
            <img src="~/img/Karatzas_profile.jpg" class="project-img" alt="">
            <div class="project-content">
                <h1 class="project-title">Dimitris Karatzas</h1>
                <p class="project-info">
                    Always looking for the more sophisticated way out, both in code and real life.
                    Aspiring Software Developer. Visionary with sunglasses.
                    Loving father of two (dogs).
                </p>
                <div class="project-btn-grp">
                    <a href="https://github.com/dimitriskaratzas" target="_blank" class="project-btn github"><button class="project-btn github">github</button></a>
                    <a href="https://www.linkedin.com/in/dimitris-karatzas-473133195/" target="_blank" class="project-btn live"><button class="project-btn live">LinkedIn profile</button></a>
                </div>
            </div>
        </div>
        <div class="project-card">
            <img src="~/img/Amitsis_profile.jpeg" class="project-img" alt="">
            <div class="project-content">
                <h1 class="project-title">Filippos Amitsis</h1>
                <p class="project-info">
                    Forward-looking Junior Software Engineer, sometimes an Accountant.
                    Things in life change all the time. One thing that won't is his passion for race cars.
                    If you need more proof, if you were to spell racecar backwards it's still a racecar.
                    <div class="project-btn-grp">
                        <a href="https://github.com/FilipposNC" target="_blank" class="project-btn github"><button class="project-btn github">github</button></a>
                        <a href="https://www.linkedin.com/in/filippos-amitsis-484931226/" target="_blank" class="project-btn live"><button class="project-btn live">LinkedIn profile</button></a>
                    </div>
</div>
        </div>
        <div class="project-card">
            <img src="~/img/Gatsakos_profile.jpeg" class="project-img" alt="">
            <div class="project-content mpampis">
                <h1 class="project-title">Charalampos Gatsakos</h1>
                <p class="project-info">
                    He worked with a range of development technologies.
                    Front-End Experience with:
                    React , Angular , Html , Css

                    Back-End Experience with:
                    C# ASP.Net , Node , MSSQL
                </p>
                <div class="project-btn-grp">
                    <a href="https://github.com/charalampos-gatsakos" target="_blank" class="project-btn github"><button class="project-btn github">github</button></a>
                    <a href="https://www.linkedin.com/in/charalampos-gatsakos-66a069201/" target="_blank" class="project-btn live"><button class="project-btn live">LinkedIn profile</button></a>
                </div>
            </div>
        </div>
    </div>
</section>

GroupProject/Views/Home/Contact.cshtml
@*@{
        ViewBag.Title = "Contact";
    }
    <h2>@ViewBag.Title</h2>*@



<!-- contact section -->
<section class="contact-section">
    <form action="https://getform.io/f/3d1d85ab-5841-462d-a492-e94ae404f542" method="POST" name="contact-form" id="contact-form" class="contact-form">
        <div class="input-control">
            <input type="text" name="name" id="name" autocomplete="off" placeholder="Name">
            <div class="error"></div>
        </div>
        <div class="input-control">
            <input type="text" name="email" id="email" autocomplete="off" placeholder="Email">
            <div class="error"></div>
        </div>
        <div class="input-control">
            <textarea name="msg" id="msg" placeholder="Message" autocomplete="off"></textarea>
            <div class="error"></div>
        </div>
        <button id="submit-btn" type="submit" class="form-submit-btn">contact</button>
    </form>

    <!-- map -->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12573.66280672845!2d23.6884175!3d38.0140872!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa8435b54cc257e11!2sArch%20Beer%20House!5e0!3m2!1sel!2sgr!4v1641373060490!5m2!1sel!2sgr"
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
</section>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            // Initialize form validation on the registration form.
            // It has the name attribute "registration"
            $("form[name='contact-form']").validate({
                // Specify validation rules
                rules: {
                    // The key name on the left side is the name attribute
                    // of an input field. Validation rules are defined
                    // on the right side
                    name: "required",
                    msg: "required",
                    email: {
                        required: true,
                        // Specify that email should be validated
                        // by the built-in "email" rule
                        email: true
                    },
                },
                // Specify validation error messages
                messages: {
                    name: " Please enter your name",
                    msg: " Please fill the form",
                    email: " Please enter a valid email address"
                },
                // Make sure the form is submitted to the destination defined
                // in the "action" attribute of the form when valid
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

GroupProject/Views/Home/Help.cshtml
@{
    ViewBag.Title = "Help";
}

<div class="help">
    <h2 class="links">How to use this site:</h2>

    <p>If you want to build a new PC and don't know where to start, or how to combine a CPU with a compatible motherboard, look no further.</p>
    <p>The Delegays Project provides you with the tools necessary to achieve that sweat-free. Here are some basic tips on how to navigate around the website.</p>
    <br />
    <div>
        <ul>
            <li><strong class="links">All Parts:</strong> Here you can view all the seperate Pc Parts and view their details, so you can prepare before assembling a build.</li>
            <li><strong class="links">Suggested Builds:</strong> You can come to this section, if you just want to browse builds, made by our all powerfull, all knowing Admins.</li>
            <li>
                <strong class="links">System Builder:</strong> The heart and soul of the site. Here you can create your own build. When you choose a Pc part, its details will be shown to your right.
                <br />What's even more, once you choose a Cpu, only the compatible motherboards will appear to you!
            </li>
            <li><strong class="links">My Builds:</strong> Once you create a build, it will be listed here.</li>
            <li><strong class="links">All Builds:</strong> Here you can find the builds created by all the users.</li>
            <li><strong class="links">Donate:</strong> This is the last place to visit before leaving the site. If you were happy with our services, toss a coin to your witchers!</li>
        </ul>
    </div>
</div>

GroupProject/Views/Home/Index.cshtml
        @Html.Partial("_SuggestedBuilds")
        @Html.Partial("_UserBuilds")

GroupProject/Views/Home/PCParts.cshtml
<link href="~/Content/StyleSheetBabis.css"  rel="stylesheet" />


<div class="container">
<div class="containers" styles="margin: 0 auto;">
    <div class="row">
        <div class="col-md-4 card card1">
            <div class="imgBx">
                <img src="~/img/ryzen-chip-1.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>CPU</h2>
                <br />
                <a href="@Url.Action("Index", "CPUs")">View All</a>
            </div>
        </div>
        <div class="col-md-4 card card2">
            <div class="imgBx">
                <img src="~/img/mobopng.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>Motherboards</h2>
                <br />
                <a href="@Url.Action("Index", "Motherboards")">View All</a>
            </div>
        </div>
        <div class="col-md-4 card card3" >
            <div class="imgBx">
                <img src="~/img/casepng.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>Cases</h2>
                <br />
                <a href="@Url.Action("Index", "Cases")">View All</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 card card4">
            <div class="imgBx">
                <img src="~/img/rampng.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>RAM</h2>
                <br />
                <a href="@Url.Action("Index", "RAMs")">View All</a>
            </div>
        </div>
        <div class="col-md-4 card card5">
            <div class="imgBx">
                <img src="~/img/ssdpng.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>Storage</h2>
                <br />
                <a href="@Url.Action("Index", "Storages")">View All</a>
            </div>
        </div>
        <div class="col-md-4 card card6">
            <div class="imgBx">
                <img src="~/img/psupng.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>PSU</h2>
                <br />
                <a href="@Url.Action("Index", "PSUs")">View All</a>
            </div>
        </div>
    </div>  
    <div class="row">
        <div class="col-md-4 card card7" style="margin-left: 31%;">
            <div class="imgBx">
                <img src="~/img/graphics_card_tp.png">
            </div>
            <div class="contentBx">
                <br />
                <br />
                <h2>GPU</h2>
                <br />
                <a href="@Url.Action("Index", "GPUs")">View All</a>
            </div>
        </div>
    </div>
    </div>
</div>




 